export const TEST_SOUNDS = {
  1: [{ file: './sounds/1.mp3', hasS3: true }],
  2: [{ file: './sounds/2.mp3', hasS3: true }],
  3: [{ file: './sounds/3.mp3', hasS3: true }],
  4: [{ file: './sounds/1.mp3', hasS3: true }],
  5: [{ file: './sounds/2.mp3', hasS3: true }],
  6: [{ file: './sounds/3.mp3', hasS3: true }],
  7: [{ file: './sounds/1.mp3', hasS3: true }],
  8: [{ file: './sounds/2.mp3', hasS3: true }],
  9: [{ file: './sounds/3.mp3', hasS3: true }],
  10: [{ file: './sounds/1.mp3', hasS3: true }],
};

export const SOUNDS = {
  7: [
    { file: './sounds/S3_7v2.wav', hasS3: true },
    { file: './sounds/S3_7v3.wav', hasS3: true },
    { file: './sounds/S3_7v1.wav', hasS3: true },
    { file: './sounds/S3_7v4.wav', hasS3: true },
    { file: './sounds/S3_7v5.wav', hasS3: true },
    { file: './sounds/S3_7final.wav', hasS3: true },
  ],
  10: [
    { file: './sounds/S3_10v5.wav', hasS3: true },
    { file: './sounds/S3_10v4.wav', hasS3: true },
    { file: './sounds/S3_10v3.wav', hasS3: true },
    { file: './sounds/S3_10final.wav', hasS3: true },
    { file: './sounds/S3_10v2.wav', hasS3: true },
    { file: './sounds/S3_10v1.wav', hasS3: true },
  ],
  1: [
    { file: './sounds/S3_1v4.wav', hasS3: true },
    { file: './sounds/S3_1v5.wav', hasS3: true },
    { file: './sounds/S3_1final.wav', hasS3: true },
    { file: './sounds/S3_1v2.wav', hasS3: true },
    { file: './sounds/S3_1v3.wav', hasS3: true },
    { file: './sounds/S3_1v1.wav', hasS3: true },
  ],
  5: [
    { file: './sounds/S3_5v1.wav', hasS3: true },
    { file: './sounds/S3_5v3.wav', hasS3: true },
    { file: './sounds/S3_5v2.wav', hasS3: true },
    { file: './sounds/S3_5v5.wav', hasS3: true },
    { file: './sounds/S3_5v4.wav', hasS3: true },
    { file: './sounds/S3_5final.wav', hasS3: true },
  ],
  3: [
    { file: './sounds/S3_3v5.wav', hasS3: true },
    { file: './sounds/S3_3v4.wav', hasS3: true },
    { file: './sounds/S3_3v1.wav', hasS3: true },
    { file: './sounds/S3_3v3.wav', hasS3: true },
    { file: './sounds/S3_3v2.wav', hasS3: true },
    { file: './sounds/S3_3final.wav', hasS3: true },
  ],
  2: [
    { file: './sounds/S3_2v5.wav', hasS3: true },
    { file: './sounds/S3_2v4.wav', hasS3: true },
    { file: './sounds/S3_2v3.wav', hasS3: true },
    { file: './sounds/S3_2v2.wav', hasS3: true },
    { file: './sounds/S3_2v1.wav', hasS3: true },
    { file: './sounds/S3_2final.wav', hasS3: true },
  ],
  6: [
    { file: './sounds/S3_6v1.wav', hasS3: true },
    { file: './sounds/S3_6v2.wav', hasS3: true },
    { file: './sounds/S3_6v3.wav', hasS3: true },
    { file: './sounds/S3_6final.wav', hasS3: true },
    { file: './sounds/S3_6v4.wav', hasS3: true },
    { file: './sounds/S3_6v5.wav', hasS3: true },
  ],
  4: [
    { file: './sounds/S3_4v3.wav', hasS3: true },
    { file: './sounds/S3_4v2.wav', hasS3: true },
    { file: './sounds/S3_4v1.wav', hasS3: true },
    { file: './sounds/S3_4v5.wav', hasS3: true },
    { file: './sounds/S3_4v4.wav', hasS3: true },
    { file: './sounds/S3_4final.wav', hasS3: true },
  ],
  8: [
    { file: './sounds/S3_8v4.wav', hasS3: true },
    { file: './sounds/S3_8v5.wav', hasS3: true },
    { file: './sounds/S3_8v1.wav', hasS3: true },
    { file: './sounds/S3_8final.wav', hasS3: true },
    { file: './sounds/S3_8v2.wav', hasS3: true },
    { file: './sounds/S3_8v3.wav', hasS3: true },
  ],
  9: [
    { file: './sounds/S3_9final.wav', hasS3: true },
    { file: './sounds/S3_9v4.wav', hasS3: true },
    { file: './sounds/S3_9v5.wav', hasS3: true },
    { file: './sounds/S3_9v2.wav', hasS3: true },
    { file: './sounds/S3_9v3.wav', hasS3: true },
    { file: './sounds/S3_9v1.wav', hasS3: true },
  ],
};
