export const SOUNDS = {
  calibration: './sounds/calibration.mp3',

  7: [
    { file: './sounds/S3_7v2.mp3', hasS3: true },
    { file: './sounds/S3_7v3.mp3', hasS3: true },
    { file: './sounds/S3_7v1.mp3', hasS3: true },
    { file: './sounds/S3_7v4.mp3', hasS3: true },
    { file: './sounds/S3_7v5.mp3', hasS3: true },
    { file: './sounds/S3_7final.mp3', hasS3: true },
    { file: './sounds/S3_7final2.mp3', hasS3: true },
  ],
  10: [
    { file: './sounds/S3_10v5.mp3', hasS3: true },
    { file: './sounds/S3_10v4.mp3', hasS3: true },
    { file: './sounds/S3_10v3.mp3', hasS3: true },
    { file: './sounds/S3_10final.mp3', hasS3: true },
    { file: './sounds/S3_10v2.mp3', hasS3: true },
    { file: './sounds/S3_10v1.mp3', hasS3: true },
    { file: './sounds/S3_10final2.mp3', hasS3: true },
  ],
  1: [
    { file: './sounds/S3_1v4.mp3', hasS3: true },
    { file: './sounds/S3_1v5.mp3', hasS3: true },
    { file: './sounds/S3_1final.mp3', hasS3: true },
    { file: './sounds/S3_1v2.mp3', hasS3: true },
    { file: './sounds/S3_1v3.mp3', hasS3: true },
    { file: './sounds/S3_1v1.mp3', hasS3: true },
    { file: './sounds/S3_1final2.mp3', hasS3: true },
  ],
  5: [
    { file: './sounds/S3_5v1.mp3', hasS3: true },
    { file: './sounds/S3_5v3.mp3', hasS3: true },
    { file: './sounds/S3_5v2.mp3', hasS3: true },
    { file: './sounds/S3_5v5.mp3', hasS3: true },
    { file: './sounds/S3_5v4.mp3', hasS3: true },
    { file: './sounds/S3_5final.mp3', hasS3: true },
    { file: './sounds/S3_5final2.mp3', hasS3: true },
  ],
  3: [
    { file: './sounds/S3_3v5.mp3', hasS3: true },
    { file: './sounds/S3_3v4.mp3', hasS3: true },
    { file: './sounds/S3_3v1.mp3', hasS3: true },
    { file: './sounds/S3_3v3.mp3', hasS3: true },
    { file: './sounds/S3_3v2.mp3', hasS3: true },
    { file: './sounds/S3_3final.mp3', hasS3: true },
    { file: './sounds/S3_3final2.mp3', hasS3: true },
  ],
  2: [
    { file: './sounds/S3_2v5.mp3', hasS3: true },
    { file: './sounds/S3_2v4.mp3', hasS3: true },
    { file: './sounds/S3_2v3.mp3', hasS3: true },
    { file: './sounds/S3_2v2.mp3', hasS3: true },
    { file: './sounds/S3_2v1.mp3', hasS3: true },
    { file: './sounds/S3_2final.mp3', hasS3: true },
    { file: './sounds/S3_2final2.mp3', hasS3: true },
  ],
  6: [
    { file: './sounds/S3_6v1.mp3', hasS3: true },
    { file: './sounds/S3_6v2.mp3', hasS3: true },
    { file: './sounds/S3_6v3.mp3', hasS3: true },
    { file: './sounds/S3_6final.mp3', hasS3: true },
    { file: './sounds/S3_6v4.mp3', hasS3: true },
    { file: './sounds/S3_6v5.mp3', hasS3: true },
    { file: './sounds/S3_6final2.mp3', hasS3: true },
  ],
  4: [
    { file: './sounds/S3_4v3.mp3', hasS3: true },
    { file: './sounds/S3_4v2.mp3', hasS3: true },
    { file: './sounds/S3_4v1.mp3', hasS3: true },
    { file: './sounds/S3_4v5.mp3', hasS3: true },
    { file: './sounds/S3_4v4.mp3', hasS3: true },
    { file: './sounds/S3_4final.mp3', hasS3: true },
    { file: './sounds/S3_4final2.mp3', hasS3: true },
  ],
  8: [
    { file: './sounds/S3_8v4.mp3', hasS3: true },
    { file: './sounds/S3_8v5.mp3', hasS3: true },
    { file: './sounds/S3_8v1.mp3', hasS3: true },
    { file: './sounds/S3_8final.mp3', hasS3: true },
    { file: './sounds/S3_8v2.mp3', hasS3: true },
    { file: './sounds/S3_8v3.mp3', hasS3: true },
    { file: './sounds/S3_8final2.mp3', hasS3: true },
  ],
  9: [
    { file: './sounds/S3_9final.mp3', hasS3: true },
    { file: './sounds/S3_9v4.mp3', hasS3: true },
    { file: './sounds/S3_9v5.mp3', hasS3: true },
    { file: './sounds/S3_9v2.mp3', hasS3: true },
    { file: './sounds/S3_9v3.mp3', hasS3: true },
    { file: './sounds/S3_9v1.mp3', hasS3: true },
    { file: './sounds/S3_9final2.mp3', hasS3: true },
  ],
};
